apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuaHVhd2VpY2xvdWQuY29tIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6ImhhcmJvckB3dXFpYW5eaHFqMTIzIiwiYXV0aCI6IllXUnRhVzQ2YUdGeVltOXlRSGQxY1dsaGJsNW9jV294TWpNPSJ9fX0=
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: kubectl
    operation: Update
  name: harborsecret
  namespace: xxl-job
  resourceVersion: "16039393"
  uid: ec790717-682a-4883-887c-2797c964b5fe
type: kubernetes.io/dockerconfigjson
